server:
  port: 8080
  # servlet:
  #   context-path: /test-api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

spring:
  application:
    name: turtle-base
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL # 序列化时，只序列化非空字段
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/turtle-base?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0 #数据库索引
      timeout: 5000 #连接超时时间
      lettuce:
        pool:
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
  cache:
    # 缓存类型 redis、none(不使用缓存)
    type: redis
    # 缓存时间(单位：ms)
    redis:
      time-to-live: 3600000
      # 缓存null值，防止缓存穿透
      cache-null-values: true
  devtools:
    restart:
      enabled: true
      include:
        include:
          com-company-core: /com-company-core-[\\w\\d-\\.]+\\.jar
          com-company-module: /com-company-module-[\\w\\d-\\.]+\\.jar

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.kecoyo.*.model

# Ali OSS访问配置
aliyun:
  oss:
    access-key-id: LTAI5********vaNG
    access-key-secret: J7scH********oXTuR
    region-id: oss-cn-beijing
    endpoint: oss-cn-beijing.aliyuncs.com
    internal-endpoint: oss-cn-beijing-internal.aliyuncs.com
    internal: false
    bucket-name: lj********re
    domain: https://lj********re.oss-cn-beijing.aliyuncs.com

springdoc:
  api-docs:
    # 是否开启接口文档
    enabled: true
  swagger-ui:
    # 是否开启Swagger UI
    enabled: true
    # 持久化认证数据，如果设置为 true，它会保留授权数据并且不会在浏览器关闭/刷新时丢失
    persistAuthorization: true

jwt:
  header: Authorization
  # 令牌前缀
  token-start-with:
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认2小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 7200000
  # 在线用户key
  online-key: "online-token:"
  # 验证码
  code-key: "captcha-code:"
  # token 续期检查时间范围（默认30分钟，单位默认毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认 1小时，这里单位毫秒
  renew: 3600000

login:
  user-cache:
    enabled: false
    #
    key: "user-login-cache:"
    # 存活时间/秒
    idle-time: 21600

# 项目配置
project:
  # 本地文件目录
  local-dir: D:\\tmp\\
  # oss文件目录
  oss-dir: pst/jingshibei/tmp/
  # 任务处理的线程数
  thread-count: 1
  # 删除本地文件
  delete-local-file: true
