spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/turtle-butler?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
      timeout: 5000
