server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

spring:
  application:
    name: turtle-base
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null # 序列化时，只序列化非空字段
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/turtle_open?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0 #数据库索引
      timeout: 5000 #连接超时时间
      lettuce:
        pool:
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
  cache:
    # 缓存类型 redis、none(不使用缓存)
    type: redis
    # 缓存时间(单位：ms)
    redis:
      time-to-live: 3600000
      # 缓存null值，防止缓存穿透
      cache-null-values: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.kecoyo.*.model

# Ali OSS访问配置
aliyun:
  oss:
    access-key-id: LTAI5********vaNG
    access-key-secret: J7scH********oXTuR
    region-id: oss-cn-beijing
    endpoint: oss-cn-beijing.aliyuncs.com
    internal-endpoint: oss-cn-beijing-internal.aliyuncs.com
    internal: false
    bucket-name: lj********re
    domain: https://lj********re.oss-cn-beijing.aliyuncs.com

springdoc:
  swagger-ui:
    enabled: true
